version: '3.8'
services:
  mongo:
    image: 'mongo:latest'
    restart: 'always'
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
      - './db:/data/db'
    container_name: 'mongo'
    logging:
      driver: none
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_USERNAME
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - MONGO_PORT=$MONGO_PORT
    ports:
      - '27017:27017'
  indexer:
    build: './indexer'
    restart: 'always'
    volumes:
      - './indexer:/indexer'
      - './shared:/shared'
    depends_on:
      - 'mongo'
    links:
      - 'mongo'
    env_file: .env
    environment:
      - MONGO_USERNAME=$DATABASE_USERNAME
      - MONGO_PASSWORD=$DATABASE_PASSWORD
      - MONGO_PORT=$MONGO_PORT
      - MONGO_HOST=$MONGO_HOST
  # web:
  #   build: './web'
  #   restart: 'always'
  #   volumes:
  #     - './web:/web'
  #     - './shared:/shared'
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - 'mongo'
  #   links:
  #     - 'mongo'
  #   env_file: .env
  #   environment:
  #     - MONGO_USERNAME=$DATABASE_USERNAME
  #     - MONGO_PASSWORD=$DATABASE_PASSWORD
  #     - MONGO_PORT=$MONGO_PORT
  #     - MONGO_HOST=$MONGO_HOST

