version: '3.8'
services:
  mongo:
    image: 'mongo:latest'
    restart: 'always'
    ports:
      - '27017:27017'
    volumes:
      - './db:/data/db'
    container_name: 'mongo'
    logging:
      driver: none
  indexer:
    build: './indexer'
    restart: 'always'
    depends_on:
      - 'mongo'
    volumes:
      - './indexer:/indexer'
      - './shared:/shared'
  # web:
  #   build: './web'
  #   restart: 'always'
  #   depends_on:
  #     - 'mongo'
  #   volumes:
  #     - './web:/web'
  #     - './shared:/shared'
  #   ports:
  #     - '8080:8080'

